#! /usr/bin/env sh
Red='\033[0;31m'
Color_Off='\033[0m' 
Green='\033[0;32m'

# Check if python is available
pyapp=`which python`
if [ "${pyapp:0:1}" == "/" ]
then
    python --version
else
    echo "Python not found"
    exit
fi

# Check if the script has been given
script=$1
if [ -z "${1}" ]
then
    echo "No python script specified"
    exit
fi

# Check if the given script exists
if [ ! -f "${script}" ]
then
    echo "File not found: ${script}"
    exit
fi

# Run tests
python hello.py > .test/hello.out
diff .test/exp01.txt .test/hello.out > .test/d01.out
nb01=`cat .test/d01.out | wc -l`
rm .test/hello.out
if [ ${nb01} -eq 0 ]
then
    echo "  ${Green}\xE2\x9C\x94${Color_Off} Test 1"
else
    echo "  ${Red}\xE2\x9C\x97${Color_Off} Test 1"
    echo "Expected"
    grep "<" .test/d01.out
    echo "Given"
    grep ">" .test/d01.out
fi
